from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="your_package_name",
    version="0.1.0",
    author="Your Name",
    author_email="your@email.com",
    description="Your package description",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/your_username/your_package",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.11",
    install_requires=[
        "addict==2.4.0",
        "attrs==23.2.0",
        "blinker==1.7.0",
        "certifi==2024.2.2",
        "charset-normalizer==3.3.2",
        "click==8.1.7",
        "ConfigArgParse==1.7",
        "contourpy==1.2.0",
        "cycler==0.12.1",
        "dash==2.15.0",
        "dash-core-components==2.0.0",
        "dash-html-components==2.0.0",
        "dash-table==5.0.0",
        "fastjsonschema==2.19.1",
        "Flask==3.0.2",
        "fonttools==4.49.0",
        "idna==3.6",
        "importlib-metadata==7.0.1",
        "itsdangerous==2.1.2",
        "Jinja2==3.1.3",
        "joblib==1.3.2",
        "jsonschema==4.21.1",
        "jsonschema-specifications==2023.12.1",
        "jupyter_core==5.7.1",
        "kiwisolver==1.4.5",
        "MarkupSafe==2.1.5",
        "matplotlib==3.8.3",
        "nbformat==5.9.2",
        "nest-asyncio==1.6.0",
        "numpy==1.26.4",
        "open3d==0.18.0",
        "packaging==23.2",
        "pandas==2.2.0",
        "pillow==10.2.0",
        "platformdirs==4.2.0",
        "plotly==5.19.0",
        "pyparsing==3.1.1",
        "pyquaternion==0.9.9",
        "python-dateutil==2.8.2",
        "pytz==2024.1",
        "PyYAML==6.0.1",
        "referencing==0.33.0",
        "requests==2.31.0",
        "retrying==1.3.4",
        "rpds-py==0.18.0",
        "scikit-learn==1.4.1.post1",
        "scipy==1.12.0",
        "six==1.16.0",
        "tenacity==8.2.3",
        "threadpoolctl==3.3.0",
        "tqdm==4.66.2",
        "traitlets==5.14.1",
        "typing_extensions==4.9.0",
        "tzdata==2024.1",
        "urllib3==2.2.1",
        "Werkzeug==3.0.1",
        "zipp==3.17.0"
    ],
)